'use client';
import { motion } from 'framer-motion';
import { GraduationCap, Search, FileCheck2, MessageCircle, Send, Plane, Globe2, ArrowUpRight, Quote } from 'lucide-react';
import { SectionHeading } from '../section-heading';
import { ApplyNowDialog } from '../ui/apply-now-dialog';
import { TrustStrip } from '../trust-strip';
const guidance=[{icon:MessageCircle,title:'Counselling',text:'Understand your goals, profile and options with practical one-to-one guidance.'},{icon:Search,title:'Selection of University & Program',text:'Compare destinations, universities and programs that fit your academic direction.'},{icon:FileCheck2,title:'University Admission / Enrollment',text:'Get structured support through applications, documents and enrollment steps.'}];
const process=[{icon:MessageCircle,title:'Consultation'},{icon:Send,title:'Apply'},{icon:Globe2,title:'Globe'},{icon:GraduationCap,title:'Appointment'},{icon:Plane,title:'Fly'}];
const fallbackTestimonials=[['Ayesha Rahman','Monash University','The guidance made a complicated process feel clear and manageable.'],['Tanvir Hasan','University of Auckland','I always knew what the next step was and who to ask.'],['Nabila Islam','University of Toronto','GAP helped me choose with confidence instead of guessing.']];
const fallbackNews=['Study destination checklist: where should you start?','How to prepare a stronger university application','What to consider when choosing your program','Planning your timeline for studying abroad','Documents to prepare before you apply','Making your first counselling session count'];
export function Hero(){return <section className="hero-wrap"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-28"><div><p className="eyebrow">Global education, human guidance</p><h1 className="display-xl mt-5">Your next chapter starts <em>globally.</em></h1><p className="mt-6 max-w-xl text-base leading-8 text-[var(--muted)] sm:text-lg">Personal guidance, trusted university choices, and practical admission support for students planning to study abroad.</p><div className="mt-8 flex flex-wrap gap-3"><ApplyNowDialog triggerClass="touch-target rounded-full bg-[var(--primary)] px-6 py-3 font-semibold text-white"/><a href="#process" className="touch-target rounded-full border border-[var(--border)] px-6 py-3 font-semibold">How it works</a></div><div className="mt-7"><TrustStrip /></div><div className="mt-10 flex gap-8 text-sm"><div><strong className="font-display text-2xl">3</strong><span className="ml-2 text-[var(--muted)]">launch destinations</span></div><div><strong className="font-display text-2xl">1:1</strong><span className="ml-2 text-[var(--muted)]">guidance</span></div></div></div><div className="hero-art"><div className="hero-card"><span>GAP</span><p className="font-display text-4xl leading-tight sm:text-5xl">From ambition<br/>to admission.</p><div className="mt-12 flex items-center justify-between text-sm"><span>Plan</span><span>Prepare</span><span>Go</span></div></div></div></div></section>}
export function About(){return <section className="border-y border-[var(--border)]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.7fr_1.3fr] lg:px-8 lg:py-28"><SectionHeading eyebrow="About us" title="A clearer path to your next chapter."/><div><p className="font-display text-3xl leading-tight sm:text-4xl">Study abroad should feel exciting — not overwhelming.</p><p className="mt-6 max-w-2xl leading-8 text-[var(--muted)]">GAP brings together counselling, university and program selection, and admission support into one guided journey. The goal is simple: help students make informed choices and move forward with confidence.</p></div></div></section>}
export function AcademicGuidance(){return <section><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="Academic guidance" title="Support at the moments that matter." text="Three practical stages, connected by one consistent team."/><div className="mt-12 grid gap-4 md:grid-cols-3">{guidance.map((x,i)=>{const I=x.icon;return <motion.article whileInView={{opacity:1,y:0}} initial={{opacity:0,y:20}} viewport={{once:true}} transition={{duration:.3,delay:i*.06}} key={x.title} className="card-lift rounded-[1.75rem] border border-[var(--border)] p-7 sm:p-8"><div className="flex size-12 items-center justify-center rounded-2xl bg-[var(--surface)] text-[var(--primary)]"><I size={23}/></div><p className="mt-10 text-sm font-semibold text-[var(--muted)]">0{i+1}</p><h3 className="mt-2 font-display text-2xl leading-tight">{x.title}</h3><p className="mt-4 leading-7 text-[var(--muted)]">{x.text}</p></motion.article>})}</div></div></section>}
export function HowGapWorks(){return <section id="process" className="bg-[var(--surface)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="How GAP works" title="One step at a time, all the way to the globe." text="A simple journey with clear hand-offs between every stage."/><div className="process-track mt-14">{process.map((x,i)=>{const I=x.icon;return <motion.div key={x.title} whileInView={{opacity:1,scale:1}} initial={{opacity:0,scale:.92}} viewport={{once:true}} className={`process-node ${i===2?'process-center':''}`}><div className="process-icon"><I size={22}/></div><span>{x.title}</span></motion.div>})}</div></div></section>}
export function Testimonials({items=[]}:{items?:Array<{studentName:string;universityName?:string;quote:string}>}){const testimonials=items.length?items.map(x=>[x.studentName,x.universityName||'GAP student',x.quote]):fallbackTestimonials;return <section><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><SectionHeading eyebrow="What our clients say" title="Confidence feels different when you don't have to do it alone."/><div className="mt-12 flex snap-x gap-4 overflow-x-auto pb-3 md:grid md:grid-cols-3 md:overflow-visible">{testimonials.map(([name,uni,quote])=><article key={name} className="min-w-[85%] snap-start rounded-[1.75rem] border border-[var(--border)] p-7 sm:min-w-[55%] md:min-w-0"><Quote size={28} className="text-[var(--primary)]"/><p className="mt-7 font-display text-2xl leading-snug">“{quote}”</p><div className="mt-8 border-t border-[var(--border)] pt-5"><strong>{name}</strong><p className="mt-1 text-sm text-[var(--muted)]">{uni}</p></div></article>)}</div></div></section>}
export function NewsFeed({items=[]}:{items?:Array<{title:string;slug?:string;shortBlurb?:string;publishedDate?:string}>}){const news=items.length?items.map(x=>x.title):fallbackNews;return <section className="bg-[var(--surface)]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex items-end justify-between gap-5"><SectionHeading eyebrow="News feed" title="Useful things to know before you go."/><span className="hidden text-sm text-[var(--muted)] sm:block">Latest {Math.min(news.length,6)}</span></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{news.map((n,i)=><article key={n} className="card-lift rounded-[1.5rem] border border-[var(--border)] bg-[var(--background)] p-6"><div className="aspect-[16/9] rounded-2xl bg-[#dfe8df] p-5"><span className="text-sm font-semibold">0{i+1}</span></div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-[var(--muted)]">GAP Journal</p><h3 className="mt-2 font-display text-2xl leading-tight">{n}</h3><a href={items[i]?.slug ? `/news/${items[i].slug}` : "/news"} className="mt-5 inline-flex items-center gap-1 text-sm font-bold">Read more <ArrowUpRight size={16}/></a></article>)}</div></div></section>}
export function Partners(){const partners=['Monash University','University of Auckland','University of Toronto','Deakin University','University of Sydney'];return <section><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-20"><p className="eyebrow text-center">Our partners</p><div className="marquee mt-10"><div className="marquee-track">{[...partners,...partners].map((p,i)=><div className="partner-pill" key={`${p}-${i}`}><GraduationCap size={18}/>{p}</div>)}</div></div></div></section>}
export function FinalCta(){return <section className="px-5 pb-20 lg:px-8 lg:pb-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-[2rem] bg-[var(--primary)] p-8 text-white sm:p-12 lg:flex-row lg:items-center"><div><p className="eyebrow text-white/70">Ready when you are</p><h2 className="mt-3 font-display text-4xl sm:text-5xl">Let's map your route to the world.</h2></div><ApplyNowDialog triggerClass="touch-target rounded-full bg-white px-6 py-3 font-semibold text-[var(--primary)]"/></div></section>}
