'use client';
import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { CheckCircle2, Loader2, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
type Option={id:string|number;name:string;country?:string|number};
const initial={studentName:'',email:'',phone:'',countryId:'',universityId:'',studyLevel:'',intake:'',message:''};
export function ApplicationForm(){
 const [form,setForm]=useState(initial); const [countries,setCountries]=useState<Option[]>([]); const [universities,setUniversities]=useState<Option[]>([]);
 const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle'); const [error,setError]=useState(''); const [reference,setReference]=useState('');
 useEffect(()=>{fetch('/api/application-options').then(r=>r.json()).then(d=>{setCountries(d.countries||[]);setUniversities(d.universities||[])}).catch(()=>{})},[]);
 const available=useMemo(()=>universities.filter(u=>!form.countryId||String(u.country)===String(form.countryId)),[universities,form.countryId]);
 function update(name:string,value:string){setForm(v=>({...v,[name]:value,...(name==='countryId'?{universityId:''}:{})}));setStatus('idle');setError('')}
 async function submit(e:FormEvent){e.preventDefault();setStatus('loading');setError('');try{const r=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,universityId:form.universityId||null,sourcePage:location.pathname})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to submit application.');setReference(d.reference);setStatus('success');setForm(initial)}catch(e){setStatus('error');setError(e instanceof Error?e.message:'Unable to submit application.')}}
 if(status==='success')return <div className="rounded-[2rem] border border-[var(--border)] p-8 text-center sm:p-12"><CheckCircle2 size={50} className="mx-auto text-emerald-600"/><h2 className="mt-5 font-display text-4xl">Application received.</h2><p className="mt-3 text-muted-foreground">Keep this reference for your records.</p><div className="mx-auto mt-6 max-w-sm rounded-2xl bg-[var(--surface)] px-5 py-4 font-mono font-semibold">{reference}</div><p className="mt-5 text-sm text-muted-foreground">A GAP adviser can review your profile and update the application from the admin workspace.</p></div>;
 return <form onSubmit={submit} className="grid gap-5 rounded-[2rem] border border-[var(--border)] p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><Input required  aria-label="Full name" placeholder="Full name" value={form.studentName} onChange={e=>update('studentName',e.target.value)}/><Input required type="email"  aria-label="Email address" placeholder="Email address" value={form.email} onChange={e=>update('email',e.target.value)}/><Input  aria-label="Phone number" placeholder="Phone number" value={form.phone} onChange={e=>update('phone',e.target.value)}/><Select name="studyLevel" required value={form.studyLevel} onValueChange={value=>update('studyLevel',value)}><SelectTrigger aria-label="Study level"><SelectValue placeholder="Study level" /></SelectTrigger><SelectContent>{['Foundation','Undergraduate','Postgraduate','PhD','Other'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select name="countryId" required value={form.countryId} onValueChange={value=>update('countryId',value)}><SelectTrigger aria-label="Destination"><SelectValue placeholder="Destination" /></SelectTrigger><SelectContent>{countries.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select><Select name="universityId" value={form.universityId || 'none'} onValueChange={value=>update('universityId',value === 'none' ? '' : value)}><SelectTrigger aria-label="University (optional)"><SelectValue placeholder="University (optional)" /></SelectTrigger><SelectContent><SelectItem value="none">University (optional)</SelectItem>{available.map(x=><SelectItem key={x.id} value={String(x.id)}>{x.name}</SelectItem>)}</SelectContent></Select><Input className="sm:col-span-2" aria-label="Preferred intake, e.g. February 2027" placeholder="Preferred intake, e.g. February 2027" value={form.intake} onChange={e=>update('intake',e.target.value)}/></div><Textarea className="min-h-32" aria-label="Tell us about your study goals or anything we should know" placeholder="Tell us about your study goals or anything we should know" value={form.message} onChange={e=>update('message',e.target.value)}/><div className="rounded-2xl bg-[var(--surface)] p-4 text-sm leading-6 text-muted-foreground">After submission, a GAP adviser will review your profile and explain how to provide any required documents securely.</div>{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}<Button type="submit" disabled={status==='loading'}>{status==='loading'?<Loader2 className="animate-spin" size={17}/>:<Send size={17}/>} {status==='loading'?'Submitting…':'Submit application'}</Button></form>
}
