import Image from "next/image";
import { stockImage } from "@/lib/stock-images";
import { AnimatedDisclosure } from "@/components/ui/animated-disclosure";
import { GraduationCap, MapPin, Languages, Clock3 } from "lucide-react";
import { canadaStudyGuide as guide } from "@/lib/canada-study-guide";

function Source({ href, children }: { href: string; children: string }) {
  return <a href={href} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex text-xs text-primary underline underline-offset-4">{children}</a>;
}
function GuideTable({ headers, rows, caption }: { headers: string[]; rows: string[][]; caption: string }) {
  return <div className="mt-6 overflow-x-auto rounded-xl border border-border"><table className="w-full text-left text-sm"><caption className="sr-only">{caption}</caption><thead className="bg-primary/10"><tr>{headers.map(header => <th key={header} scope="col" className="px-4 py-4 font-semibold">{header}</th>)}</tr></thead><tbody className="divide-y divide-border">{rows.map(row => <tr key={row[0]} className="even:bg-surface/50">{row.map((cell, i) => i === 0 ? <th key={i} scope="row" className="px-4 py-4 font-medium">{cell}</th> : <td key={i} className="px-4 py-4 leading-6 text-muted-foreground">{cell}</td>)}</tr>)}</tbody></table></div>;
}
export function CanadaFacts() {
  const cards = [
    { title: "Education", Icon: GraduationCap, rows: [["3–4 years", "Typical bachelor’s degree"], ["1–2 years", "Typical master’s degree"], ["24 hours / week", "Eligible off-campus work during classes"], ["Up to 3 years", "PGWP for eligible graduates"]] },
    { title: "Country at a glance", Icon: MapPin, rows: [["Ottawa", "Capital city"], ["CAD", "Canadian dollar"], ["English & French", "Official languages"], ["10 provinces · 3 territories", "Regional study settings"]] },
    { title: "Plan for your arrival", Icon: Languages, rows: [["Four seasons", "Weather varies by region"], ["Winter preparation", "Plan clothing and transport"], ["Campus location", "Compare housing and commute"], ["Language of study", "Check each course’s requirements"]] },
  ];
  return <section id="key-facts" className="my-9 scroll-mt-48 rounded-2xl bg-surface p-5 sm:p-8"><h2 className="text-center font-display text-2xl sm:text-3xl">Key facts about studying in Canada</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{cards.map(({ title, Icon, rows }) => <div key={title} className="rounded-xl bg-background/70 p-5"><h3 className="flex items-center gap-2 text-sm font-semibold"><Icon size={18} aria-hidden="true" className="text-primary" />{title}</h3><dl className="mt-4 space-y-4">{rows.map(([value, label]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 text-lg font-semibold">{value}</dd></div>)}</dl></div>)}</div><div className="flex flex-wrap gap-x-5"><Source href={guide.sources.pathways}>Study pathways: EduCanada</Source><Source href={guide.sources.work}>Work conditions: IRCC</Source><Source href={guide.sources.pgwp}>PGWP eligibility: IRCC</Source></div></section>;
}
export function CanadaGuideSection({ id }: { id: string }) {
  if (id === "requirements") return <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{guide.requirements.map(([title, description]) => <AnimatedDisclosure key={title} title={title}><p>{description}</p></AnimatedDisclosure>)}</div><Source href={guide.sources.permit}>Official study permit document checklist</Source></>;
  if (id === "intakes") return <><GuideTable headers={["Intake", "Typical start", "Availability"]} rows={guide.intakes} caption="Canadian academic start periods" /><p className="mt-3 text-xs leading-6 text-muted-foreground">Start dates and application deadlines vary by institution and program. A semester date does not guarantee a new admissions intake.</p><Source href={guide.sources.dates}>Example academic calendar: UBC</Source></>;
  if (id === "programs") return <><GuideTable headers={["Qualification", "Typical duration", "Study focus"]} rows={guide.durations} caption="Study qualifications and typical durations in Canada" /><Source href={guide.sources.pathways}>Qualification pathways: EduCanada</Source><h3 className="mt-8 font-display text-2xl">Popular subjects to explore</h3><ul className="mt-4 flex flex-wrap gap-3">{guide.subjects.map(subject => <li key={subject} className="rounded-full bg-primary/10 px-4 py-2 text-sm">{subject}</li>)}</ul></>;
  if (id === "costs") return <><GuideTable headers={["Budget item", "Amount in CAD", "Basis"]} rows={guide.costs} caption="Canadian tuition averages and budget categories" /><p className="mt-3 text-xs leading-6 text-muted-foreground">These are dated national averages, not course quotations. Confirm current tuition directly with your institution. BDT equivalents vary with the exchange rate.</p><Source href={guide.sources.tuition}>2025/26 tuition averages: Statistics Canada</Source></>;
  if (id === "cities") return <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{guide.cities.map(([city, province, description], i) => <article key={city} className="group overflow-hidden rounded-xl border border-border bg-surface transition-[border-color,box-shadow] duration-300 hover:border-primary/40 hover:shadow-lg motion-reduce:transition-none"><div className="relative aspect-[3/2] overflow-hidden"><Image src={city === "Toronto" ? stockImage("canada")! : `/images/cities/${city.toLowerCase().replaceAll(" ", "-")}.webp`} alt={`${city}, ${province}, Canada`} fill sizes="(min-width: 1024px) 300px, (min-width: 640px) 45vw, 90vw" className="object-cover transition-transform duration-500 motion-safe:group-hover:scale-105 motion-reduce:transition-none" /><span className="absolute right-3 top-3 rounded-full bg-background/85 px-2 py-1 text-xs text-primary">{String(i + 1).padStart(2, "0")}</span></div><div className="p-4"><h3 className="font-display text-xl">{city}</h3><p className="mt-1 text-xs text-primary">{province}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p></div></article>)}</div>;
  if (id === "work") return <div className="mt-6 grid gap-4 md:grid-cols-2">{[["Part-time work while studying", "Eligible students may work off campus for up to 24 hours per week during regular academic terms. Different conditions apply during scheduled breaks; confirm your eligibility and permit conditions.", guide.sources.work], ["Work after graduation", "Eligible graduates may receive a post-graduation work permit for up to three years. Eligibility and validity depend on the program, its length and current IRCC requirements.", guide.sources.pgwp]].map(([title, description, href]) => <article key={title} className="rounded-xl bg-surface p-6"><Clock3 size={22} aria-hidden="true" className="text-primary"/><h3 className="mt-3 font-display text-xl">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{description}</p><Source href={href}>Check current IRCC rules</Source></article>)}</div>;
  return null;
}
