export type DestinationGuide = {
  name: string; slug: string; capital: string; currency: string; language: string;
  bachelor: string; master: string; starts: string[][]; cities: string[]; subjects: string[];
  education: string; fees: string; immigration: string; costs: string[][];
};
const euPermit = (country: string) => `https://home-affairs.ec.europa.eu/policies/migration-and-asylum/eu-immigration-portal/student-${country}_en`;
const autumn = [['Autumn', 'September / October', 'Main start period; confirm course availability'], ['Spring', 'January / February', 'Selected courses only; check the institution']];
const southern = [['First semester', 'February / March', 'Confirm programme opening and deadlines'], ['Second semester', 'July', 'Selected programmes; check the institution']];
const variable = (currency: string): string[][] => [['Tuition', 'Course-specific', `Request the current fee schedule in ${currency}`], ['Accommodation and living', 'City-specific', 'Compare housing, transport and food costs'], ['Insurance and travel', 'Personal budget', 'Check cover and travel arrangements'], ['Application and residence costs', 'Depends on your circumstances', 'Check official requirements before budgeting']];
export const destinationGuides: DestinationGuide[] = [
  { name: 'Australia', slug: 'australia', capital: 'Canberra', currency: 'AUD', language: 'English is the main teaching language', bachelor: 'Usually 3 years; some courses longer', master: 'Usually 1-2 years', starts: southern, cities: ['Sydney', 'Melbourne', 'Brisbane'], subjects: ['Business', 'Engineering', 'Computing', 'Health sciences', 'Environmental science', 'Design'], education: 'https://www.studyaustralia.gov.au/en/plan-your-studies/universities-and-higher-education/undergraduate-qualifications', fees: 'https://www.studyaustralia.gov.au/en/life-in-australia/living-and-education-costs', immigration: 'https://www.studyaustralia.gov.au/en/plan-your-move/visa-application-process', costs: variable('AUD') },
  { name: 'United Kingdom', slug: 'united-kingdom', capital: 'London', currency: 'GBP', language: 'English', bachelor: 'Usually 3 years; 4 in Scotland', master: 'Often 1 year full-time', starts: autumn, cities: ['London', 'Manchester', 'Edinburgh'], subjects: ['Business', 'Law', 'Engineering', 'Design', 'Social sciences', 'Computing'], education: 'https://study-uk.britishcouncil.org/plan-studies/ways-learning/undergraduate', fees: 'https://study-uk.britishcouncil.org/moving-uk/cost-studying', immigration: 'https://www.gov.uk/student-visa', costs: [['International undergraduate tuition', 'GBP 11,400-38,000', 'Indicative range from Study UK; confirm the annual course fee'], ['International postgraduate tuition', 'GBP 9,000-30,000', 'Indicative range; confirm whether quoted per year or course'], ['Living outside London', 'GBP 900-1,300 / month', 'Study UK planning estimate for a student without dependants'], ['Living in London', 'GBP 1,300-1,400 / month', 'Study UK planning estimate; lifestyle and housing vary']] },
  { name: 'New Zealand', slug: 'new-zealand', capital: 'Wellington', currency: 'NZD', language: 'English is the main teaching language', bachelor: 'Many degrees take 3 years', master: 'Course-specific; check the provider', starts: southern, cities: ['Auckland', 'Wellington', 'Christchurch'], subjects: ['Agriculture', 'Environmental studies', 'Business', 'Technology', 'Health sciences', 'Education'], education: 'https://www.studywithnewzealand.govt.nz/en/study-options/study-options', fees: 'https://www.studywithnewzealand.govt.nz/en/plan-your-studies/cost-of-living', immigration: 'https://www.immigration.govt.nz/study/', costs: [['Bachelor tuition', 'NZD 35,000-55,000 / year', 'Official guide range, updated March 2025; some subjects cost more'], ['Postgraduate tuition', 'NZD 20,000-45,000', 'Official guide range; confirm the period covered'], ['Most PhD subjects', 'NZD 6,500-7,500 / year', 'Official guide, March 2025; provider-specific exceptions'], ['Living, insurance and travel', 'Depends on city and arrangements', 'Budget separately; check the current visa financial requirements']] },
  { name: 'United States', slug: 'united-states', capital: 'Washington, D.C.', currency: 'USD', language: 'English is the main teaching language', bachelor: 'Usually 4 years', master: 'Programme-specific', starts: [['Fall', 'August / September', 'Main start period; institution-specific'], ['Spring', 'January', 'Selected programmes'], ['Summer', 'May-August', 'Limited or programme-specific starts']], cities: ['New York City', 'Boston', 'Chicago'], subjects: ['Computing', 'Engineering', 'Business', 'Liberal arts', 'Natural sciences', 'Media'], education: 'https://educationusa.state.gov/your-5-steps-us-study/research-your-options/undergraduate', fees: 'https://educationusa.state.gov/your-5-steps-us-study/finance-your-studies', immigration: 'https://studyinthestates.dhs.gov/students', costs: variable('USD') },
  { name: 'Finland', slug: 'finland', capital: 'Helsinki', currency: 'EUR', language: 'Finnish and Swedish; English-taught options', bachelor: 'Programme-specific; university or UAS route', master: 'Programme-specific; check eligibility', starts: autumn, cities: ['Helsinki', 'Tampere', 'Turku'], subjects: ['Technology', 'Design', 'Business', 'Environmental studies', 'Education', 'Computing'], education: 'https://www.studyinfinland.fi/admissions/bachelors-and-masters-admissions', fees: 'https://www.studyinfinland.fi/funding-your-studies/fees-and-cost-living', immigration: 'https://migri.fi/en/studying-in-finland', costs: [['English-taught bachelor and master tuition', 'EUR 9,000-20,000 / year', 'Typical non-EU/EEA/Swiss range; exemptions and course exceptions apply'], ['Living expenses', 'EUR 900-1,200 / month', 'Recommended planning budget; not a visa funds calculation'], ['Application fee', 'EUR 100', 'Non-EU/EEA/Swiss applicants; check exemptions'], ['Doctoral tuition', 'No tuition fees', 'Funding and living costs must still be planned']] },
  { name: 'Sweden', slug: 'sweden', capital: 'Stockholm', currency: 'SEK', language: 'Swedish; English-taught options', bachelor: 'Check programme credits and duration', master: 'Check programme credits and duration', starts: autumn, cities: ['Stockholm', 'Gothenburg', 'Lund'], subjects: ['Engineering', 'Sustainability', 'Business', 'Design', 'Life sciences', 'Computing'], education: 'https://www.universityadmissions.se/en/', fees: 'https://www.universityadmissions.se/en/fees-scholarships-residence-permit/', immigration: 'https://www.migrationsverket.se/en/you-want-to-apply/study.html', costs: variable('SEK') },
  { name: 'Denmark', slug: 'denmark', capital: 'Copenhagen', currency: 'DKK', language: 'Danish; selected English-taught courses', bachelor: 'University and professional routes differ', master: 'Check the individual programme', starts: autumn, cities: ['Copenhagen', 'Aarhus', 'Odense'], subjects: ['Engineering', 'Business', 'Architecture', 'Life sciences', 'Design', 'Technology'], education: 'https://studyindenmark.dk/study-options', fees: 'https://education.ec.europa.eu/sv/study-in-europe/country-profiles/denmark', immigration: 'https://www.nyidanmark.dk/en-GB/You-want-to-apply/Study/Higher-education', costs: variable('DKK') },
  { name: 'Switzerland', slug: 'switzerland', capital: 'Bern (federal city)', currency: 'CHF', language: 'German, French, Italian and Romansh; course language varies', bachelor: 'Check institution and qualification', master: 'Check institution and qualification', starts: autumn, cities: ['Zurich', 'Geneva', 'Lausanne'], subjects: ['Hospitality', 'Business', 'Engineering', 'Life sciences', 'Finance', 'Design'], education: 'https://www.swissuniversities.ch/en/topics/studying', fees: 'https://www.swissuniversities.ch/en/themen/lehre-studium/information-on-studies/tuition-fees/tuition-fees-at-universities', immigration: 'https://www.sem.admin.ch/sem/en/home/themen/aufenthalt.html', costs: variable('CHF') },
  { name: 'Austria', slug: 'austria', capital: 'Vienna', currency: 'EUR', language: 'German; selected English-taught programmes', bachelor: 'Usually 6 semesters (3 years)', master: 'Usually 4 semesters (2 years)', starts: autumn, cities: ['Vienna', 'Graz', 'Innsbruck'], subjects: ['Engineering', 'Business', 'Music', 'Social sciences', 'Computing', 'Arts'], education: 'https://studyinaustria.at/en/plan-your-studies/find-your-programme', fees: 'https://studyinaustria.at/en/tuition', immigration: 'https://studyinaustria.at/en/plan-your-studies/entry', costs: [['Public university tuition', 'Generally EUR 726.72 / semester', 'Third-country students with a Residence Permit-Student; exemptions apply'], ['Applied sciences and private institutions', 'Institution-specific', 'Check the provider fee schedule'], ['Accommodation and living', 'City-specific', 'Budget housing, food and transport separately'], ['Insurance and travel', 'Personal budget', 'Check residence and insurance requirements']] },
  { name: 'Germany', slug: 'germany', capital: 'Berlin', currency: 'EUR', language: 'German; English-taught programmes available', bachelor: 'Check course credits and curriculum', master: 'Check course credits and curriculum', starts: [['Winter semester', 'September / October', 'Check institution and programme opening'], ['Summer semester', 'March / April', 'Selected programmes only']], cities: ['Berlin', 'Munich', 'Hamburg'], subjects: ['Engineering', 'Computing', 'Business', 'Natural sciences', 'Design', 'Social sciences'], education: 'https://www.daad.de/en/studying-in-germany/', fees: 'https://www.daad.de/en/studying-in-germany/living-in-germany/finances/', immigration: 'https://www.make-it-in-germany.com/en/visa-residence/types/studying', costs: [['Public institution tuition', 'Often no tuition; exceptions apply', 'State, institution and programme rules vary; private courses differ'], ['Semester contribution', 'EUR 70-430 / semester', 'DAAD indicative range, separate from tuition'], ['Living expenses', 'EUR 900-1,200 / month', 'DAAD planning range; housing and city affect the budget'], ['Non-EU tuition exceptions', 'Check your institution', 'Fees can apply in Baden-Wuerttemberg, Bavaria and particular courses']] },
  { name: 'Malta', slug: 'malta', capital: 'Valletta', currency: 'EUR', language: 'Maltese and English; check course delivery', bachelor: 'Check recognised qualification and credits', master: 'Check course delivery and duration', starts: autumn, cities: ['Msida', 'Valletta', 'Saint Julian\'s'], subjects: ['Business', 'Hospitality', 'Computing', 'Language studies', 'Health sciences', 'Maritime studies'], education: 'https://www.um.edu.mt/study/admissionsadvice/international/', fees: 'https://www.um.edu.mt/study/admissionsadvice/international/', immigration: euPermit('malta'), costs: variable('EUR') },
  { name: 'Poland', slug: 'poland', capital: 'Warsaw', currency: 'PLN', language: 'Polish; English-taught programmes available', bachelor: 'Usually 3-4 years', master: 'Usually 1.5-2 years', starts: autumn, cities: ['Warsaw', 'Krakow', 'Wroclaw'], subjects: ['Medicine', 'Engineering', 'Computing', 'Business', 'Natural sciences', 'Arts'], education: 'https://study.gov.pl/', fees: 'https://study.gov.pl/tuition-fees', immigration: euPermit('poland'), costs: [['Tuition', 'EUR 2,000-6,000 / year', 'Official guide range; institution and subject exceptions apply'], ['MBA tuition', 'About EUR 8,000-12,000 / year', 'Official guide estimate; confirm current programme fees'], ['Accommodation and living', 'City-specific (PLN)', 'Plan housing, transport and daily spending separately'], ['Insurance, travel and application costs', 'Personal budget', 'Check current provider and immigration requirements']] },
  { name: 'Lithuania', slug: 'lithuania', capital: 'Vilnius', currency: 'EUR', language: 'Lithuanian; English-taught programmes available', bachelor: 'University and college routes differ', master: 'Check programme admission and duration', starts: autumn, cities: ['Vilnius', 'Kaunas', 'Klaipeda'], subjects: ['Business', 'Engineering', 'Computing', 'Health sciences', 'Design', 'Social sciences'], education: 'https://studyin.lt/', fees: 'https://studyin.lt/', immigration: euPermit('lithuania'), costs: variable('EUR') },
];
export function getDestinationGuide(name: string) { return destinationGuides.find(guide => guide.name === name); }
export const guideRequirements = [
  ['Academic records', 'Prepare certificates and transcripts. Qualification recognition and entry grades depend on the institution and course.'],
  ['Language evidence', 'Check accepted tests, course-specific scores and whether an exemption is available directly with the institution.'],
  ['Study statement', 'Explain your interests and study goals if a personal statement or motivation letter is requested.'],
  ['References', 'Arrange academic or professional references where the programme requires them.'],
  ['Identity documents', 'Prepare your passport and any identity documents requested by the institution.'],
  ['Portfolio or assessment', 'Some programmes request a portfolio, interview or admissions test; check the course requirements.'],
  ['Student permission', 'After receiving an offer, check the official student visa or residence permit process for your circumstances.'],
  ['Financial and insurance evidence', 'Check current official funding and insurance requirements rather than relying on a general tuition estimate.'],
];
